Underneath, in this notebook, you may find the prepared, e.t. filled with proper math and logic dataset, which performs greatly (>top 3%) even with untuned Deep Learning Model, which for this task is not suitable (obviously it do requires ML model, due to the highly dispersed low number of elements data datasets).

In [33]:
#Imports
import tensorflow as tf
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from google.colab.data_table import DataTable # Comment this line if not on Collab
pd.set_option('display.max_columns', None) # Comment this line if not on Collab
DataTable.max_columns = 30 # Comment this line if not on Collab

In [34]:
# Getting the data from github
!wget -O test.csv https://raw.githubusercontent.com/LozinskiMatthew/Titanic-DL-Kaggle_Competition/main/test.csv
!wget -O train.csv https://raw.githubusercontent.com/LozinskiMatthew/Titanic-DL-Kaggle_Competition/main/train.csv
test_data = pd.read_csv('../content/test.csv')
train_data = pd.read_csv('../content/train.csv')

--2025-02-04 17:37:06--  https://raw.githubusercontent.com/LozinskiMatthew/Titanic-DL-Kaggle_Competition/main/test.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28210 (28K) [text/plain]
Saving to: ‘test.csv’

test.csv            100%[===================>]  27.55K  --.-KB/s    in 0.002s

2025-02-04 17:37:06 (14.8 MB/s) - ‘test.csv’ saved [28210/28210]

--2025-02-04 17:37:06--  https://raw.githubusercontent.com/LozinskiMatthew/Titanic-DL-Kaggle_Competition/main/train.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 60302 (59K) [text/plain]
Saving to: ‘train.csv’

train.csv           100%[===================>]  58.89K  --.-KB/s    in 0.01s

2025-02-04 17:37:06 (3.97 MB/s) - ‘train.csv’ saved [60302/60302]

In [35]:
# Data cleansed, additionally PCA was adjusted,
finding_patterns = pd.concat([train_data, test_data], axis=0) # Name finding patterns was made, in the bigger verions, where I did extensive data exploration
train_data['Age'] = train_data['Age'].fillna(value=finding_patterns['Age'].mean())
train_data['Fare'] = train_data['Fare'].fillna(value=finding_patterns['Fare'].mean())
test_data['Age'] = test_data['Age'].fillna(value=finding_patterns['Age'].mean())
test_data['Fare'] = test_data['Fare'].fillna(value=finding_patterns['Fare'].mean())
train_data['Embarked'] = train_data['Embarked'].fillna(value='S') # There are two Nans, thus I wont create a new column, it's not worth it to make more dimensions (+ S dominates)
train_data['LetterInCabin'] = train_data['Cabin'].str[0]
test_data['LetterInCabin'] = test_data['Cabin'].str[0]
train_data = train_data.drop(['Cabin'], axis=1)
test_data = test_data.drop(['Cabin'], axis=1)
train_data['Name'].str.extract('([A-Za-z]+)\.', expand=True)
train_data['Name'] = train_data['Name'].str.extract('([A-Za-z]+)\.', expand=True)
train_data.loc[train_data['Age'] < 15, 'Name'] = 'Kid' # The crew considered them to be children
train_data['LetterInCabin'] = train_data['LetterInCabin'].fillna(value='N')
test_data['Name'] = test_data['Name'].str.extract('([A-Za-z]+)\.', expand=True)
test_data.loc[test_data['Age'] < 15, 'Name'] = 'Kid'
test_data['LetterInCabin'] = test_data['LetterInCabin'].fillna(value='N')

In [36]:
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,LetterInCabin
0,1,0,3,Mr,male,22.0,1,0,A/5 21171,7.2500,S,N
1,2,1,1,Mrs,female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,Miss,female,26.0,0,0,STON/O2. 3101282,7.9250,S,N
3,4,1,1,Mrs,female,35.0,1,0,113803,53.1000,S,C
4,5,0,3,Mr,male,35.0,0,0,373450,8.0500,S,N

In [37]:
# Normalization
scaler = MinMaxScaler()

ready_train_dataset_scaled = scaler.fit_transform(train_data.drop(['Sex', 'Survived', 'Pclass', 'Ticket', 'Embarked', 'LetterInCabin', 'Name'], axis=1))
ready_train_dataset_scaled_df = pd.DataFrame(data=ready_train_dataset_scaled, columns=train_data.drop(['Sex', 'Survived', 'Pclass', 'Ticket', 'Embarked', 'LetterInCabin', 'Name'], axis=1).columns)
train_data = pd.concat([train_data.drop(['PassengerId', 'Age', 'SibSp', 'Parch', 'Fare'], axis=1), ready_train_dataset_scaled_df], axis=1)

ready_test_dataset_scaled = scaler.transform(test_data.drop(['Sex', 'Pclass', 'Ticket', 'Embarked', 'LetterInCabin', 'Name'], axis=1))
ready_test_dataset_scaled_df = pd.DataFrame(data=ready_test_dataset_scaled, columns=test_data.drop(['Sex', 'Pclass', 'Ticket', 'Embarked', 'LetterInCabin', 'Name'], axis=1).columns)
test_data = pd.concat([test_data.drop(['PassengerId', 'Age', 'SibSp', 'Parch', 'Fare'], axis=1), ready_test_dataset_scaled_df], axis=1)

In [38]:
train_data['LetterInCabin'].value_counts()

LetterInCabin
N    687
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: count, dtype: int64

In [39]:
# Standardization will be better if you were to decide to work with ML models, which will perform better

'''
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

ready_train_dataset_scaled = scaler.fit_transform(train_data.drop(['Sex', 'Survived', 'Pclass', 'Ticket', 'Embarked', 'LetterInCabin', 'Name'], axis=1))
ready_train_dataset_scaled_df = pd.DataFrame(data=ready_train_dataset_scaled, columns=train_data.drop(['Sex', 'Survived', 'Pclass', 'Ticket', 'Embarked', 'LetterInCabin', 'Name'], axis=1).columns)
train_data = pd.concat([train_data.drop(['PassengerId', 'Age', 'SibSp', 'Parch', 'Fare'], axis=1), ready_train_dataset_scaled_df], axis=1)

ready_test_dataset_scaled = scaler.fit_transform(test_data.drop(['Sex', 'Pclass', 'Ticket', 'Embarked', 'LetterInCabin', 'Name'], axis=1))
ready_test_dataset_scaled_df = pd.DataFrame(data=ready_test_dataset_scaled, columns=test_data.drop(['Sex', 'Pclass', 'Ticket', 'Embarked', 'LetterInCabin', 'Name'], axis=1).columns)
test_data = pd.concat([test_data.drop(['PassengerId', 'Age', 'SibSp', 'Parch', 'Fare'], axis=1), ready_test_dataset_scaled_df], axis=1)

'''

"\nfrom sklearn.preprocessing import StandardScaler\n\nscaler = StandardScaler()\n\nready_train_dataset_scaled = scaler.fit_transform(train_data.drop(['Sex', 'Survived', 'Pclass', 'Ticket', 'Embarked', 'LetterInCabin', 'Name'], axis=1))\nready_train_dataset_scaled_df = pd.DataFrame(data=ready_train_dataset_scaled, columns=train_data.drop(['Sex', 'Survived', 'Pclass', 'Ticket', 'Embarked', 'LetterInCabin', 'Name'], axis=1).columns)\ntrain_data = pd.concat([train_data.drop(['PassengerId', 'Age', 'SibSp', 'Parch', 'Fare'], axis=1), ready_train_dataset_scaled_df], axis=1)\n\nready_test_dataset_scaled = scaler.fit_transform(test_data.drop(['Sex', 'Pclass', 'Ticket', 'Embarked', 'LetterInCabin', 'Name'], axis=1))\nready_test_dataset_scaled_df = pd.DataFrame(data=ready_test_dataset_scaled, columns=test_data.drop(['Sex', 'Pclass', 'Ticket', 'Embarked', 'LetterInCabin', 'Name'], axis=1).columns)\ntest_data = pd.concat([test_data.drop(['PassengerId', 'Age', 'SibSp', 'Parch', 'Fare'], axis=1), ready_test_dataset_scaled_df], axis=1)\n\n"

In [40]:
# OneHotEncoding
ohe = OneHotEncoder(sparse_output=False, handle_unknown='infrequent_if_exist')

embarked_encoded_train = ohe.fit_transform(train_data[['Embarked']])
embarked_train_df = pd.DataFrame(data=embarked_encoded_train, columns=ohe.categories_)
embarked_encoded_test = ohe.transform(test_data[['Embarked']])
embarked_test_df = pd.DataFrame(data=embarked_encoded_test, columns=ohe.categories_)

categories=[['male', 'female']]
ore_sex = OrdinalEncoder(categories=categories)
sex_encoded_train = ore_sex.fit_transform(train_data[['Sex']])
sex_train_df = pd.DataFrame(data=sex_encoded_train, columns=['Sex'])
sex_encoded_test = ore_sex.transform(test_data[['Sex']])
sex_test_df = pd.DataFrame(data=sex_encoded_test, columns=['Sex'])

categories = [['T', 'H', 'G', 'F', 'N', 'E', 'D', 'C', 'B', 'A']]
ore_cabin = OrdinalEncoder(categories=categories)
letter_encoded_train = ore_cabin.fit_transform(train_data[['LetterInCabin']])
letter_train_df = pd.DataFrame(data=letter_encoded_train, columns=['LetterInCabin']) # I put N before E due to the previous analysis and common sense i.e. analysis + it cannot be in the middle directly, cause the ones with lower feasibilities, were the ones that couldnt buy better tickets, and obviously we must have more data on rich people
letter_encoded_test = ore_cabin.transform(test_data[['LetterInCabin']])
letter_test_df = pd.DataFrame(data=letter_encoded_test, columns=['LetterInCabin'])

ticket_encoded_train = ohe.fit_transform(train_data[['Ticket']])
ticket_train_df = pd.DataFrame(data=ticket_encoded_train, columns=ohe.categories_)
ticket_encoded_test = ohe.transform(test_data[['Ticket']])
ticket_test_df = pd.DataFrame(data=ticket_encoded_test, columns=ohe.categories_)

name_encoded_train = ohe.fit_transform(train_data[['Name']])
name_train_df = pd.DataFrame(data=name_encoded_train, columns=ohe.categories_)
name_encoded_test = ohe.transform(test_data[['Name']])
name_test_df = pd.DataFrame(data=name_encoded_test, columns=ohe.categories_)

final_train_data = pd.concat([train_data.drop(['Sex', 'Ticket', 'Embarked', 'LetterInCabin', 'Name'], axis=1), embarked_train_df, sex_train_df, letter_train_df, ticket_train_df, name_train_df], axis=1)
final_test_data = pd.concat([test_data.drop(['Sex', 'Ticket', 'Embarked', 'LetterInCabin', 'Name'], axis=1), embarked_test_df, sex_test_df, letter_test_df, ticket_test_df, name_test_df], axis=1)
final_test_data = final_test_data.reindex(columns=final_train_data.columns, fill_value=0.0)
final_test_data.drop(columns=['Survived'], inplace=True)

In [41]:
# Float64 convergence, you may need it in some cases, and it does not hurt the algorithm.
final_train_data['SibSp'] =  final_train_data['SibSp'].astype('float64')
final_train_data['Parch'] =  final_train_data['Parch'].astype('float64')
final_train_data['Survived'] =  final_train_data['Survived'].astype('float64')

final_test_data['SibSp'] =  final_test_data['SibSp'].astype('float64')
final_test_data['Parch'] =  final_test_data['Parch'].astype('float64')
final_test_data['PassengerId'] =  final_test_data['PassengerId'].astype('float64')

In [42]:
# Creating final datasets to work with.
final_train_data_labels = final_train_data.drop(columns=['Survived'])
final_train_data_target = final_train_data['Survived']
train_labels_np = final_train_data_labels.to_numpy()
train_target_np = final_train_data_target.to_numpy()
test_np = final_test_data.to_numpy()

In [43]:
#For training your models, experimenting with your models, you should use validation dataset, e.t. uncomment below, and use it for fit, and add proper callbacks
'''
divisor = np.round(float(len(final_train_data)) * 85 / 100)
divisor = int(divisor)
train_np_labels = final_train_data_labels[:divisor].to_numpy()
train_np_labels = final_train_data_target[:divisor].to_numpy()
valid_np_labels = final_train_data_labels[divisor:].to_numpy()
valid_np_target = final_train_data_target[divisor:].to_numpy()
'''

'\ndivisor = np.round(float(len(final_train_data)) * 85 / 100)\ndivisor = int(divisor)\ntrain_np_labels = final_train_data_labels[:divisor].to_numpy()\ntrain_np_labels = final_train_data_target[:divisor].to_numpy()\nvalid_np_labels = final_train_data_labels[divisor:].to_numpy()\nvalid_np_target = final_train_data_target[divisor:].to_numpy()\n'

In [44]:
# Func with Callbacks, were you to choose validation dataset, remember to uncomment these lines, tip. you can do it simultaneously via holding alt key, and pointing directions then ctrl+/
class CallbackCreator(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs=None):
    print(f"Epoch {epoch+1}:")
    print(f" - Loss: {logs['loss']}")
    print(f" - Accuracy: {logs['accuracy']}")
    print(f" - Precision: {logs['precision']}")
    # print(f" - Validation Loss: {logs['val_loss']}")
    # print(f" - Validation mae: {logs['val_accuracy']}")
    # print(f" = Validation Precision: {logs['val_precision']}")

That is the place for your model, were you to choose to go with DL, just write your model below, but in ML case, you should uncomment the standardization, and comment the normalization cell.

And beneath, lies a way to add to your model, final results, e.t. survived or not, just replace model_0 with  your current model name.

In [45]:
early_stopping = tf.keras.callbacks.EarlyStopping(monitor='accuracy', patience=7, restore_best_weights=True)

In [52]:
# Your model_0, random model that scores in top 3% with DL

model_0 = tf.keras.Sequential([
    tf.keras.layers.Dense(80, activation='relu'),
    tf.keras.layers.Dense(60, activation='relu'),
    tf.keras.layers.Dense(40, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

loss = tf.keras.losses.BinaryFocalCrossentropy()
optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)
model_0.compile(loss=loss, optimizer=optimizer, metrics=['accuracy', 'precision', 'recall'])

model_0.fit(x=train_labels_np, y=train_target_np, epochs=120, verbose=1, callbacks=[CallbackCreator(), early_stopping])

Epoch 1/120
24/28 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6405 - loss: 0.1658 - precision: 0.7320 - recall: 0.0704Epoch 1:
 - Loss: 0.16293737292289734
 - Accuracy: 0.6285073161125183
 - Precision: 0.7894737124443054
28/28 ━━━━━━━━━━━━━━━━━━━━ 7s 23ms/step - accuracy: 0.6384 - loss: 0.1653 - precision: 0.7415 - recall: 0.0660
Epoch 2/120
21/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6356 - loss: 0.1562 - precision: 0.9048 - recall: 0.0411Epoch 2:
 - Loss: 0.1542862355709076
 - Accuracy: 0.6487092971801758
 - Precision: 1.0
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.6377 - loss: 0.1558 - precision: 0.9310 - recall: 0.0514
Epoch 3/120
26/28 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6805 - loss: 0.1507 - precision: 0.9655 - recall: 0.2258Epoch 3:
 - Loss: 0.1465526670217514
 - Accuracy: 0.7227833867073059
 - Precision: 0.9439252614974976
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.6848 - loss: 0.1502 - precision: 0.9635 - recall: 0.2330
Epoch 4/120
27/28 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7427 - loss: 0.1413 - precision: 0.9547 - recall: 0.3846Epoch 4:
 - Loss: 0.1381772756576538
 - Accuracy: 0.7586981058120728
 - Precision: 0.9379310607910156
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7438 - loss: 0.1411 - precision: 0.9535 - recall: 0.3855
Epoch 5/120
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7767 - loss: 0.1315 - precision: 0.9153 - recall: 0.4641Epoch 5:
 - Loss: 0.13072535395622253
 - Accuracy: 0.7867564558982849
 - Precision: 0.8584905862808228
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.7771 - loss: 0.1314 - precision: 0.9133 - recall: 0.4664
Epoch 6/120
24/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8084 - loss: 0.1255 - precision: 0.8439 - recall: 0.6265Epoch 6:
 - Loss: 0.12482894957065582
 - Accuracy: 0.81144779920578
 - Precision: 0.8346154093742371
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8090 - loss: 0.1254 - precision: 0.8425 - recall: 0.6283
Epoch 7/120
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8393 - loss: 0.1182 - precision: 0.8435 - recall: 0.6888Epoch 7:
 - Loss: 0.11996515095233917
 - Accuracy: 0.8305274844169617
 - Precision: 0.8523985147476196
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8390 - loss: 0.1183 - precision: 0.8438 - recall: 0.6884
Epoch 8/120
25/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8409 - loss: 0.1133 - precision: 0.8413 - recall: 0.7235Epoch 8:
 - Loss: 0.11622681468725204
 - Accuracy: 0.8316498398780823
 - Precision: 0.8116883039474487
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8395 - loss: 0.1136 - precision: 0.8371 - recall: 0.7243
Epoch 9/120
25/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7999 - loss: 0.1184 - precision: 0.8057 - recall: 0.6980Epoch 9:
 - Loss: 0.1131904348731041
 - Accuracy: 0.8193041682243347
 - Precision: 0.7836990356445312
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8025 - loss: 0.1176 - precision: 0.8024 - recall: 0.7026
Epoch 10/120
26/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8267 - loss: 0.1123 - precision: 0.8127 - recall: 0.7159Epoch 10:
 - Loss: 0.11029453575611115
 - Accuracy: 0.8350168466567993
 - Precision: 0.8305084705352783
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8276 - loss: 0.1121 - precision: 0.8145 - recall: 0.7160
Epoch 11/120
25/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8409 - loss: 0.1065 - precision: 0.7981 - recall: 0.7801Epoch 11:
 - Loss: 0.1076137125492096
 - Accuracy: 0.8327721953392029
 - Precision: 0.8025078177452087
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8398 - loss: 0.1067 - precision: 0.7990 - recall: 0.7757
Epoch 12/120
23/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8401 - loss: 0.1091 - precision: 0.8274 - recall: 0.7811Epoch 12:
 - Loss: 0.10558490455150604
 - Accuracy: 0.8327721953392029
 - Precision: 0.8006230592727661
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8384 - loss: 0.1083 - precision: 0.8206 - recall: 0.7752
Epoch 13/120
27/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8626 - loss: 0.0967 - precision: 0.8568 - recall: 0.7665Epoch 13:
 - Loss: 0.10316158831119537
 - Accuracy: 0.8428731560707092
 - Precision: 0.8258064389228821
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8613 - loss: 0.0971 - precision: 0.8547 - recall: 0.7653
Epoch 14/120
27/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8248 - loss: 0.1042 - precision: 0.7820 - recall: 0.7510Epoch 14:
 - Loss: 0.10087650269269943
 - Accuracy: 0.8406285047531128
 - Precision: 0.8164557218551636
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8259 - loss: 0.1040 - precision: 0.7844 - recall: 0.7512
Epoch 15/120
19/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8524 - loss: 0.0910 - precision: 0.8399 - recall: 0.7786Epoch 15:
 - Loss: 0.09866082668304443
 - Accuracy: 0.8372614979743958
 - Precision: 0.8049535751342773
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8474 - loss: 0.0936 - precision: 0.8284 - recall: 0.7746
Epoch 16/120
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8292 - loss: 0.0995 - precision: 0.8096 - recall: 0.7322Epoch 16:
 - Loss: 0.0966937467455864
 - Accuracy: 0.8439955115318298
 - Precision: 0.8201892971992493
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8297 - loss: 0.0994 - precision: 0.8100 - recall: 0.7332
Epoch 17/120
27/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8716 - loss: 0.0922 - precision: 0.8780 - recall: 0.7956Epoch 17:
 - Loss: 0.0944075807929039
 - Accuracy: 0.854096531867981
 - Precision: 0.8441558480262756
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8704 - loss: 0.0923 - precision: 0.8757 - recall: 0.7932
Epoch 18/120
27/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8633 - loss: 0.0912 - precision: 0.8610 - recall: 0.7708Epoch 18:
 - Loss: 0.09187271445989609
 - Accuracy: 0.8552188277244568
 - Precision: 0.840255618095398
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8628 - loss: 0.0913 - precision: 0.8595 - recall: 0.7707
Epoch 19/120
23/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8566 - loss: 0.0948 - precision: 0.8477 - recall: 0.7638Epoch 19:
 - Loss: 0.08959972113370895
 - Accuracy: 0.8630751967430115
 - Precision: 0.8481012582778931
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8584 - loss: 0.0935 - precision: 0.8480 - recall: 0.7684
Epoch 20/120
27/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8659 - loss: 0.0890 - precision: 0.8527 - recall: 0.7944Epoch 20:
 - Loss: 0.08752802014350891
 - Accuracy: 0.868686854839325
 - Precision: 0.8571428656578064
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8661 - loss: 0.0889 - precision: 0.8530 - recall: 0.7941
Epoch 21/120
15/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8832 - loss: 0.0820 - precision: 0.8549 - recall: 0.7893  Epoch 21:
 - Loss: 0.08458641171455383
 - Accuracy: 0.8742985129356384
 - Precision: 0.8662420511245728
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8794 - loss: 0.0826 - precision: 0.8584 - recall: 0.7917
Epoch 22/120
22/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8903 - loss: 0.0774 - precision: 0.8716 - recall: 0.8364Epoch 22:
 - Loss: 0.0822359248995781
 - Accuracy: 0.8742985129356384
 - Precision: 0.8709677457809448
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.0781 - precision: 0.8710 - recall: 0.8278
Epoch 23/120
25/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8917 - loss: 0.0791 - precision: 0.8910 - recall: 0.8334Epoch 23:
 - Loss: 0.07947037369012833
 - Accuracy: 0.8810325264930725
 - Precision: 0.8641975522041321
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8902 - loss: 0.0792 - precision: 0.8877 - recall: 0.8313
Epoch 24/120
27/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8702 - loss: 0.0843 - precision: 0.8872 - recall: 0.7633Epoch 24:
 - Loss: 0.07723703980445862
 - Accuracy: 0.8866442441940308
 - Precision: 0.8899676203727722
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.0838 - precision: 0.8874 - recall: 0.7661
Epoch 25/120
15/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8769 - loss: 0.0786 - precision: 0.8191 - recall: 0.7958 Epoch 25:
 - Loss: 0.07412907481193542
 - Accuracy: 0.8933781981468201
 - Precision: 0.9022801518440247
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8825 - loss: 0.0770 - precision: 0.8563 - recall: 0.7964
Epoch 26/120
20/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9132 - loss: 0.0639 - precision: 0.9215 - recall: 0.8521Epoch 26:
 - Loss: 0.07113361358642578
 - Accuracy: 0.8933781981468201
 - Precision: 0.8920634984970093
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9072 - loss: 0.0660 - precision: 0.9117 - recall: 0.8442
Epoch 27/120
15/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8943 - loss: 0.0687 - precision: 0.9446 - recall: 0.7958 Epoch 27:
 - Loss: 0.06851260364055634
 - Accuracy: 0.9046015739440918
 - Precision: 0.9185667634010315
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9020 - loss: 0.0681 - precision: 0.9332 - recall: 0.8163
Epoch 28/120
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9128 - loss: 0.0649 - precision: 0.9212 - recall: 0.8454Epoch 28:
 - Loss: 0.06533630937337875
 - Accuracy: 0.9068462252616882
 - Precision: 0.9111111164093018
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9126 - loss: 0.0649 - precision: 0.9209 - recall: 0.8452
Epoch 29/120
27/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9136 - loss: 0.0621 - precision: 0.9183 - recall: 0.8608Epoch 29:
 - Loss: 0.06197085604071617
 - Accuracy: 0.9147025942802429
 - Precision: 0.9290322661399841
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9137 - loss: 0.0621 - precision: 0.9190 - recall: 0.8595
Epoch 30/120
27/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9188 - loss: 0.0575 - precision: 0.9270 - recall: 0.8617Epoch 30:
 - Loss: 0.058869004249572754
 - Accuracy: 0.9191918969154358
 - Precision: 0.9383116960525513
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9189 - loss: 0.0576 - precision: 0.9278 - recall: 0.8605
Epoch 31/120
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9182 - loss: 0.0584 - precision: 0.9266 - recall: 0.8579Epoch 31:
 - Loss: 0.05597126856446266
 - Accuracy: 0.9270482659339905
 - Precision: 0.9396825432777405
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9185 - loss: 0.0583 - precision: 0.9271 - recall: 0.8582
Epoch 32/120
23/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9330 - loss: 0.0512 - precision: 0.9491 - recall: 0.8621Epoch 32:
 - Loss: 0.053032245486974716
 - Accuracy: 0.9304152727127075
 - Precision: 0.9402515888214111
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9325 - loss: 0.0515 - precision: 0.9473 - recall: 0.8648
Epoch 33/120
27/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9200 - loss: 0.0522 - precision: 0.9706 - recall: 0.8217Epoch 33:
 - Loss: 0.05023464187979698
 - Accuracy: 0.936026930809021
 - Precision: 0.9581993818283081
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9211 - loss: 0.0520 - precision: 0.9698 - recall: 0.8251
Epoch 34/120
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9456 - loss: 0.0455 - precision: 0.9755 - recall: 0.8736Epoch 34:
 - Loss: 0.046918340027332306
 - Accuracy: 0.9416385889053345
 - Precision: 0.9588607549667358
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9455 - loss: 0.0456 - precision: 0.9749 - recall: 0.8740
Epoch 35/120
25/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9324 - loss: 0.0448 - precision: 0.9481 - recall: 0.8867Epoch 35:
 - Loss: 0.043884195387363434
 - Accuracy: 0.9461279511451721
 - Precision: 0.95652174949646
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9343 - loss: 0.0447 - precision: 0.9492 - recall: 0.8885
Epoch 36/120
22/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9510 - loss: 0.0371 - precision: 0.9549 - recall: 0.9121Epoch 36:
 - Loss: 0.04119178652763367
 - Accuracy: 0.9483726024627686
 - Precision: 0.9654088020324707
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9509 - loss: 0.0379 - precision: 0.9581 - recall: 0.9090
Epoch 37/120
25/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9585 - loss: 0.0386 - precision: 0.9566 - recall: 0.9373Epoch 37:
 - Loss: 0.039037372916936874
 - Accuracy: 0.9573512673377991
 - Precision: 0.9662576913833618
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9583 - loss: 0.0387 - precision: 0.9579 - recall: 0.9350
Epoch 38/120
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9612 - loss: 0.0357 - precision: 0.9865 - recall: 0.9081Epoch 38:
 - Loss: 0.03623512014746666
 - Accuracy: 0.9629629850387573
 - Precision: 0.9753845930099487
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.9613 - loss: 0.0357 - precision: 0.9861 - recall: 0.9087
Epoch 39/120
27/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9620 - loss: 0.0358 - precision: 0.9597 - recall: 0.9416Epoch 39:
 - Loss: 0.03372185677289963
 - Accuracy: 0.9674522876739502
 - Precision: 0.9728096723556519
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9624 - loss: 0.0356 - precision: 0.9606 - recall: 0.9415
Epoch 40/120
26/28 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9607 - loss: 0.0360 - precision: 0.9654 - recall: 0.9231Epoch 40:
 - Loss: 0.031844884157180786
 - Accuracy: 0.9730639457702637
 - Precision: 0.976047933101654
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.9620 - loss: 0.0356 - precision: 0.9665 - recall: 0.9261
Epoch 41/120
27/28 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9826 - loss: 0.0292 - precision: 0.9844 - recall: 0.9733Epoch 41:
 - Loss: 0.02961655892431736
 - Accuracy: 0.9764309525489807
 - Precision: 0.9734513163566589
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9821 - loss: 0.0293 - precision: 0.9836 - recall: 0.9727
Epoch 42/120
24/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9837 - loss: 0.0285 - precision: 0.9881 - recall: 0.9714Epoch 42:
 - Loss: 0.027925124391913414
 - Accuracy: 0.9831649661064148
 - Precision: 0.9794721603393555
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9836 - loss: 0.0284 - precision: 0.9867 - recall: 0.9722
Epoch 43/120
27/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9766 - loss: 0.0285 - precision: 0.9723 - recall: 0.9637Epoch 43:
 - Loss: 0.02572876587510109
 - Accuracy: 0.985409677028656
 - Precision: 0.9795918464660645
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.0283 - precision: 0.9728 - recall: 0.9650
Epoch 44/120
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9844 - loss: 0.0229 - precision: 0.9767 - recall: 0.9841Epoch 44:
 - Loss: 0.024491259828209877
 - Accuracy: 0.9842873215675354
 - Precision: 0.9767441749572754
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9844 - loss: 0.0229 - precision: 0.9767 - recall: 0.9840
Epoch 45/120
26/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9848 - loss: 0.0238 - precision: 0.9741 - recall: 0.9869Epoch 45:
 - Loss: 0.022613277658820152
 - Accuracy: 0.9865319728851318
 - Precision: 0.979651153087616
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9850 - loss: 0.0237 - precision: 0.9747 - recall: 0.9867
Epoch 46/120
24/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9898 - loss: 0.0207 - precision: 0.9890 - recall: 0.9853Epoch 46:
 - Loss: 0.021210070699453354
 - Accuracy: 0.988776683807373
 - Precision: 0.9797688126564026
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9896 - loss: 0.0208 - precision: 0.9874 - recall: 0.9863
Epoch 47/120
24/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9834 - loss: 0.0208 - precision: 0.9761 - recall: 0.9798Epoch 47:
 - Loss: 0.020386260002851486
 - Accuracy: 0.985409677028656
 - Precision: 0.9824047088623047
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0208 - precision: 0.9771 - recall: 0.9797
Epoch 48/120
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9896 - loss: 0.0189 - precision: 0.9757 - recall: 0.9959Epoch 48:
 - Loss: 0.018796825781464577
 - Accuracy: 0.9876543283462524
 - Precision: 0.9797101616859436
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9896 - loss: 0.0189 - precision: 0.9759 - recall: 0.9956
Epoch 49/120
15/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9895 - loss: 0.0180 - precision: 0.9810 - recall: 0.9918  Epoch 49:
 - Loss: 0.017737088724970818
 - Accuracy: 0.9865319728851318
 - Precision: 0.979651153087616
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9881 - loss: 0.0181 - precision: 0.9798 - recall: 0.9899
Epoch 50/120
23/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9824 - loss: 0.0177 - precision: 0.9778 - recall: 0.9773Epoch 50:
 - Loss: 0.01719888485968113
 - Accuracy: 0.9865319728851318
 - Precision: 0.979651153087616
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9831 - loss: 0.0176 - precision: 0.9780 - recall: 0.9788
Epoch 51/120
25/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9867 - loss: 0.0187 - precision: 0.9753 - recall: 0.9889Epoch 51:
 - Loss: 0.016075260937213898
 - Accuracy: 0.988776683807373
 - Precision: 0.9825581312179565
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9871 - loss: 0.0183 - precision: 0.9763 - recall: 0.9890
Epoch 52/120
23/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9901 - loss: 0.0152 - precision: 0.9861 - recall: 0.9881Epoch 52:
 - Loss: 0.015056793577969074
 - Accuracy: 0.988776683807373
 - Precision: 0.9825581312179565
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9900 - loss: 0.0151 - precision: 0.9855 - recall: 0.9884
Epoch 53/120
26/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9846 - loss: 0.0158 - precision: 0.9817 - recall: 0.9796Epoch 53:
 - Loss: 0.014513562433421612
 - Accuracy: 0.988776683807373
 - Precision: 0.9825581312179565
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9850 - loss: 0.0157 - precision: 0.9818 - recall: 0.9805

In [53]:
test_data_v2 = pd.read_csv('../content/test.csv')
final_result = pd.DataFrame(data=test_data_v2['PassengerId'], columns=['PassengerId'])
test_length = len(final_test_data)
for i in range(test_length):
  input_data = test_np[i].reshape(1, -1)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
  final_result.loc[i, 'Survived'] = prediction
  print(prediction)
final_result['Survived'] = final_result['Survived'].astype(int)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 285ms/step
1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
0

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress
<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
1

<ipython-input-53-e8a844c278e3>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  prediction = int(np.round(model_0.predict(input_data, verbose=1))) # You may set verbose to 0, lest you do not want to see the progress

At the end you can see how to save it to the file.

In [55]:
final_result.to_csv('my_submission.csv', index=False)

You may submit your results, via copying the final_result.csv to the Kaggle Compatition site.